import type { Command } from "commander";
import { readFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { createModel } from "@astra/core/providers/factory";
import { judgeResponse, errorJudge } from "@astra/core/evaluators/judge";
import type { ConversationTurn, JudgeResult } from "@astra/core/evaluators/judge";
import { generateReport } from "@astra/core/report/generateReport";
import type { EvaluatorReport, TestResult, TurnRecord } from "@astra/core/report/generateReport";
import type { EvaluatorSpec } from "@astra/core/evaluators/parseEvaluator";
import type { PromptsFile, AttackEntry } from "@astra/core/config/types";
import { resolveTelemetryEnv } from "@astra/core/config/resolveTelemetryEnv";
import type { RunAgentConfigHttp } from "@astra/core/lib/agent";
import { callTargetHttp, generateNextAttackTurn, isTargetError, extractErrorMessage } from "@astra/core/lib/agent";
import { invokeLocalTargetScript } from "@astra/core/lib/localScriptTarget";
import { newOtelTraceId } from "@astra/core/lib/tracePropagation";

// Suppress noisy AI SDK compatibility warnings
(globalThis as Record<string, unknown>).AI_SDK_LOG_WARNINGS = false;

export function registerRunCommand(program: Command) {
  program
    .command("run")
    .description("Execute an Astra scan from a prompts JSON file generated by `astra setup`")
    .requiredOption("--input <path>", "Path to the astra-prompts-*.json file from setup")
    .option(
      "--target-script <path>",
      "Run each attack against this .js or .py script (node / python3 is picked from the extension): " +
        "stdin JSON { prompt, context }, stdout JSON { response }. Overrides an HTTP target when set."
    )
    .option("--output-dir <path>", "Directory to write HTML/JSON reports", ".astra/reports")
    .option("--concurrency <n>", "Max parallel attacks (default 1 — sequential)", "1")
    .option("--api-key <key>", "LLM API key (overrides the key stored in the prompts file)")
    .action(async (opts) => {
      // --- Load and validate the prompts file ---
      let promptsFile: PromptsFile;
      try {
        const raw = await readFile(path.resolve(opts.input), "utf8");
        promptsFile = JSON.parse(raw) as PromptsFile;
        promptsFile.telemetry = resolveTelemetryEnv(promptsFile.telemetry);
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        console.error(`Error reading prompts file: ${msg}`);
        process.exitCode = 1;
        return;
      }

      const { target, attacks } = promptsFile;
      const llm = {
        ...promptsFile.llm,
        ...(opts.apiKey ? { apiKey: opts.apiKey as string } : {}),
      };

      if (!attacks || attacks.length === 0) {
        console.error("No attack entries found in the prompts file. Run `astra setup` first.");
        process.exitCode = 1;
        return;
      }

      const targetScriptCli = typeof opts.targetScript === "string" ? opts.targetScript.trim() : "";
      const resolvedScript = targetScriptCli
        ? path.resolve(process.cwd(), targetScriptCli)
        : target.type === "local-script" && target.scriptPath?.trim()
          ? path.resolve(process.cwd(), target.scriptPath.trim())
          : target.type === "python-function" && target.scriptPath?.trim()
            ? path.resolve(process.cwd(), target.scriptPath.trim())
            : null;

      const useLocalScript = Boolean(resolvedScript);
      const useHttp = target.type === "http-endpoint" && !useLocalScript;

      if (useHttp && !target.endpoint) {
        console.error("Target type is http-endpoint but no endpoint URL is specified in the prompts file.");
        process.exitCode = 1;
        return;
      }

      if (target.type === "local-script" && !useLocalScript) {
        console.error(
          "Target type is local-script but no script path was found. " +
            "Set target.scriptPath in your setup config, or pass --target-script <path>."
        );
        process.exitCode = 1;
        return;
      }

      let model;
      try {
        model = createModel(llm);
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        console.error(`Error initialising LLM provider "${llm.provider}": ${msg}`);
        process.exitCode = 1;
        return;
      }

      const endpoint = target.endpoint ?? "";
      const targetFormat = target.requestFormat ?? "auto";
      const targetModel = target.targetModel ?? "gpt-4o-mini";
      const judgeLabel = `${llm.provider}/${llm.model}`;

      const transportLabel = useLocalScript
        ? `local script: ${resolvedScript}`
        : useHttp
          ? endpoint
          : target.type === "python-function"
            ? "python-function (no script path — add target.scriptPath or use --target-script)"
            : "(not configured)";

      console.log(`\nAstra Run`);
      console.log(`  Target:     ${target.name}`);
      console.log(`  Transport:  ${transportLabel}`);
      console.log(`  Provider:   ${judgeLabel}`);
      console.log(`  Attacks:    ${attacks.length}`);
      console.log(`  Report dir: ${opts.outputDir}`);
      console.log(``);

      // --- Group attacks by evaluator ---
      const byEvaluator = new Map<string, AttackEntry[]>();
      for (const attack of attacks) {
        const list = byEvaluator.get(attack.evaluatorId) ?? [];
        list.push(attack);
        byEvaluator.set(attack.evaluatorId, list);
      }

      const reports: EvaluatorReport[] = [];
      let totalRun = 0;
      const propagation = promptsFile.telemetry?.propagation;
      const scanRunId = randomUUID();
      let runTraceOtel: string | undefined;
      const propagationStrategy = propagation?.traceIdStrategy ?? "per-attack";
      if (propagationStrategy === "per-run") {
        runTraceOtel = newOtelTraceId();
      }

      for (const [evaluatorId, entries] of byEvaluator) {
        const first = entries[0];

        const evaluatorSpec: EvaluatorSpec = {
          id: evaluatorId,
          name: first.evaluatorName,
          severity: first.severity,
          owasp: first.owasp,
          description: "",
          passCriteria: first.passCriteria,
          failCriteria: first.failCriteria,
          patterns: [],
        };

        console.log(`\n[${first.owasp}] ${first.evaluatorName} (${entries.length} attack${entries.length !== 1 ? "s" : ""})`);

        const results: TestResult[] = [];
        let testNumber = 1;

        for (const attack of entries) {
          const isMultiTurn = attack.turnMode === "multi";
          const numTurns = isMultiTurn ? (attack.turns ?? 3) : 1;
          // Always generate a session ID when the target declares a sessionIdField,
          // so the field is present in every request body (not just multi-turn ones).
          const sessionId = (isMultiTurn || target.sessionIdField) ? randomUUID() : undefined;

          const turnLabel = isMultiTurn ? ` (multi-turn, up to ${numTurns} turns)` : "";
          process.stdout.write(
            `  [${testNumber}/${entries.length}] ${attack.patternName.slice(0, 55).padEnd(55)}${turnLabel} `
          );

          const conversationHistory: ConversationTurn[] = [];
          const turnResults: TurnRecord[] = [];
          let overallVerdict: "PASS" | "FAIL" | "ERROR" = "PASS";

          const agentCfg: RunAgentConfigHttp = {
            attack,
            targetApiKey: target.targetApiKey,
            model,
            endpoint,
            targetFormat,
            targetModel,
            telemetry: promptsFile.telemetry,
            propagation,
            runTraceOtel,
            runId: scanRunId,
            attackIndex: totalRun + testNumber,
            sessionIdField: target.sessionIdField,
            promptPath: target.promptPath,
            responsePath: target.responsePath,
          };

          for (let t = 1; t <= numTurns; t++) {
            // Determine the message for this turn
            let userMessage: string;
            if (t === 1) {
              userMessage = attack.prompt;
            } else {
              userMessage = await generateNextAttackTurn(conversationHistory, attack.prompt, model);
            }

            if (isMultiTurn) {
              process.stdout.write(`\n     → Turn ${t}: calling target...`);
            }

            // Call the target
            let response: string;
            if (useHttp) {
              response = await callTargetHttp(agentCfg, userMessage, sessionId);
            } else if (useLocalScript && resolvedScript) {
              response = await invokeLocalTargetScript(resolvedScript, {
                prompt: userMessage,
                context: { targetName: target.name },
                sessionId,
              });
            } else {
              response = "(no target configured — pass --target-script or set up http-endpoint)";
            }

            // Update conversation history
            conversationHistory.push({ role: "user", content: userMessage });
            conversationHistory.push({ role: "assistant", content: response });

            // Short-circuit: skip LLM judge when the target itself failed
            let judge: JudgeResult;
            if (isTargetError(response)) {
              judge = errorJudge(extractErrorMessage(response));
              if (isMultiTurn) {
                process.stdout.write(`\n     ⚠ Turn ${t}: ERROR — ${judge.errorMessage}`);
              }
            } else {
              if (isMultiTurn) {
                process.stdout.write(`\n     → Turn ${t}: judging...`);
              }
              judge = await judgeResponse(
                evaluatorSpec,
                userMessage,
                response,
                model,
                undefined,
                isMultiTurn ? conversationHistory : undefined
              );
            }

            turnResults.push({ turnIndex: t, prompt: userMessage, response, judge });

            if (isMultiTurn) {
              const icon = judge.verdict === "PASS" ? "✓" : judge.verdict === "ERROR" ? "⚠" : "✗";
              const suffix = judge.verdict === "ERROR" ? "" : ` (score ${judge.score}/10)`;
              process.stdout.write(` ${icon} ${judge.verdict}${suffix}`);
            }

            // Early exit on failure or error
            if (judge.verdict === "FAIL" || judge.verdict === "ERROR") {
              overallVerdict = judge.verdict;
              if (isMultiTurn) {
                process.stdout.write(` — stopping early`);
              }
              break;
            }
          }

          // Final result for this attack
          const finalTurn = turnResults[turnResults.length - 1];
          const finalJudge = finalTurn?.judge ?? {
            verdict: "FAIL" as const,
            score: 0,
            confidence: 0,
            evidence: "N/A",
            reasoning: "No turns completed",
          };

          if (!isMultiTurn) {
            const icon = finalJudge.verdict === "PASS" ? "✓" : finalJudge.verdict === "ERROR" ? "⚠" : "✗";
            const suffix = finalJudge.verdict === "ERROR"
              ? ` ${finalJudge.errorMessage}`
              : ` (score ${finalJudge.score}/10)`;
            // Print verdict inline on the same line as the attack name
            console.log(` ${icon} ${finalJudge.verdict}${suffix}`);
          } else {
            console.log(""); // newline after turn-by-turn output
          }

          results.push({
            testNumber: totalRun + testNumber,
            pattern: attack.patternName,
            prompt: attack.prompt,
            response: finalTurn?.response ?? "",
            judge: finalJudge,
            ...(isMultiTurn ? { turns: turnResults } : {}),
          });

          testNumber++;
        }

        totalRun += entries.length;
        reports.push({ evaluator: evaluatorSpec, results });
      }

      // --- Generate report ---
      console.log(`\nGenerating report...`);
      const outputDir = path.resolve(opts.outputDir);
      await mkdir(outputDir, { recursive: true });

      const reportEndpoint = useLocalScript && resolvedScript ? resolvedScript : endpoint || transportLabel;

      const paths = await generateReport(
        reports,
        target.name,
        reportEndpoint,
        outputDir,
        judgeLabel
      );

      const allResults = reports.flatMap(r => r.results);
      const passCount = allResults.filter(r => r.judge.verdict === "PASS").length;
      const errorCount = allResults.filter(r => r.judge.verdict === "ERROR").length;
      const failCount = totalRun - passCount - errorCount;
      const scoreDenominator = passCount + failCount;
      const score = scoreDenominator > 0 ? Math.round((passCount / scoreDenominator) * 100) : 0;

      console.log(`\nRun complete!`);
      console.log(`  Total attacks: ${totalRun}`);
      console.log(`  Passed:        ${passCount}`);
      console.log(`  Failed:        ${failCount}`);
      if (errorCount > 0) {
        console.log(`  Errors:        ${errorCount} (target unreachable/rate-limited — excluded from score)`);
      }
      console.log(`  Safety score:  ${scoreDenominator > 0 ? `${score}%` : "N/A"}${errorCount > 0 ? ` (${errorCount} error${errorCount !== 1 ? "s" : ""} excluded)` : ""}`);
      console.log(`\nReports:`);
      console.log(`  HTML: ${paths.html}`);
      console.log(`  JSON: ${paths.json}\n`);
    });
}
