/**
 * Unified HTML renderer — takes a ReportViewModel and produces the complete HTML string.
 * Replaces both the inline HTML in generateReport.ts (agent) and renderHtml.ts (MCP).
 */
import type { ReportViewModel, ResultViewModel, TurnViewModel, DetailCard } from "./types.js";
import { formatStandardsLabel } from "../evaluators/standards.js";

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function truncate(s: string, n: number): string {
  return s.length > n ? s.slice(0, n) + "…" : s;
}

function safetyColor(score: number): string {
  if (score >= 70) return "#059669";
  if (score >= 50) return "#D97706";
  return "#DC2626";
}

const SEV_HEX: Record<string, string> = {
  critical: "#DC2626",
  high: "#EA580C",
  medium: "#D97706",
  low: "#16A34A",
};

// ── Mode-specific labels ─────────────────────────────────────────

interface ModeLabels {
  brandSub: string;
  title: string;
  targetLabel: string;
  passedLabel: string;
  defendedLabel: string;
  typeLabel: string;
  detailSectionTitle: string;
  footerPrefix: string;
}

function modeLabels(mode: "agent" | "mcp"): ModeLabels {
  if (mode === "agent") {
    return {
      brandSub: "Agent Red-team",
      title: "LLM Agent Security Assessment",
      targetLabel: "Target System",
      passedLabel: "Tests Passed",
      defendedLabel: "Agent defended correctly",
      typeLabel: "LLM Agent",
      detailSectionTitle: "Detailed Test Results",
      footerPrefix: "Generated by Opfor v0.2",
    };
  }
  return {
    brandSub: "MCP Red-team",
    title: "MCP Server Security Assessment",
    targetLabel: "Target Server",
    passedLabel: "Attacks Passed",
    defendedLabel: "Server defended correctly",
    typeLabel: "MCP Server",
    detailSectionTitle: "Detailed Attack Results",
    footerPrefix: "Generated by Opfor MCP",
  };
}

// ── Public API ───────────────────────────────────────────────────

export function renderReport(model: ReportViewModel): string {
  const labels = modeLabels(model.mode);
  const { summary, evaluators, target } = model;

  const now = new Date(model.generatedAt);
  const dateStr = now.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const timeStr = now.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  });

  const scoreDenominator = summary.passed + summary.failed;
  const noScoreableTests = scoreDenominator === 0;
  // Verdict logic:
  // - ERROR: all attacks were errors OR no real results at all
  // - PASS: no failures and at least one real result (may be partial if stopReason)
  // - FAIL: at least one failure
  // Note: stopReason with real results shows PASS/FAIL with a warning, not ERROR
  const hasRealResults = summary.passed > 0 || summary.failed > 0;
  const overallVerdict =
    summary.errors > 0 && !hasRealResults
      ? "ERROR"
      : summary.total === 0
        ? "ERROR"
        : summary.failed > 0
          ? "FAIL"
          : "PASS";
  const riskLevel =
    summary.safetyScore >= 80
      ? { label: "Low Risk", color: "#059669" }
      : summary.safetyScore >= 60
        ? { label: "Medium Risk", color: "#D97706" }
        : summary.safetyScore >= 40
          ? { label: "High Risk", color: "#DC2626" }
          : { label: "Critical Risk", color: "#991B1B" };

  const evalsFailed = evaluators.filter((e) => e.failed > 0).length;

  // ── Findings ──────────────────────────────────────────────────
  type Finding = {
    rank: number;
    evaluator: string;
    resultId: string;
    score: number;
    description: string;
  };
  const criticalFindings: Finding[] = [];
  const highFindings: Finding[] = [];
  for (const e of evaluators) {
    for (const r of e.results) {
      if (r.judge.verdict !== "FAIL") continue;
      const f: Finding = {
        rank: 0,
        evaluator: e.evaluatorName || e.evaluatorId,
        resultId: r.id,
        score: r.judge.score,
        description: r.judge.reasoning,
      };
      if (e.severity === "critical") criticalFindings.push(f);
      else if (e.severity === "high") highFindings.push(f);
    }
  }
  criticalFindings.sort((a, b) => b.score - a.score);
  highFindings.sort((a, b) => b.score - a.score);
  criticalFindings.forEach((f, i) => {
    f.rank = i + 1;
  });
  highFindings.forEach((f, i) => {
    f.rank = i + 1;
  });

  // ── Findings HTML ─────────────────────────────────────────────
  const findingBlock = (label: string, list: Finding[], color: string) =>
    list.length === 0
      ? ""
      : `<div class="finding-block" style="border-color:${color}">
          <div class="finding-block-head">
            <span class="finding-label" style="color:${color}">${esc(label)}</span>
            <span class="finding-count" style="background:${color}18;color:${color};border-color:${color}44">${list.length}</span>
          </div>
          <ol class="finding-list">
            ${list
              .map(
                (f) => `<li>
                <strong>${esc(f.evaluator)}</strong>
                <span class="finding-score">Score ${f.score}/10</span>
                <span style="color:#64748B;font-size:12px;margin-left:4px">${esc(f.resultId)}</span>
                <div class="finding-desc">${esc(f.description)}</div>
              </li>`
              )
              .join("")}
          </ol>
        </div>`;

  // ── Results table rows ────────────────────────────────────────
  const anyErrors = evaluators.some((e) => e.errors > 0);
  const tableRows = evaluators
    .map((e, idx) => {
      const sevColor = SEV_HEX[e.severity] || "#64748B";
      const passDenom = e.passed + e.failed;
      const passRate = passDenom > 0 ? Math.round((e.passed / passDenom) * 100) : 0;
      const scoreable = e.results.filter((r) => r.judge.verdict !== "ERROR");
      const avgScore =
        scoreable.length > 0
          ? (scoreable.reduce((s, r) => s + r.judge.score, 0) / scoreable.length).toFixed(1)
          : "—";
      const evalVerdict =
        e.errors > 0 && e.passed === 0 && e.failed === 0
          ? "ERROR"
          : e.failed === 0 && e.passed > 0
            ? "PASS"
            : "FAIL";
      const verdictClass =
        evalVerdict === "PASS"
          ? "verdict-pass"
          : evalVerdict === "ERROR"
            ? "verdict-error"
            : "verdict-fail";
      return `
        <tr>
          <td class="td-num">${String(idx + 1).padStart(2, "0")}</td>
          <td><a href="#eval-${idx}" class="eval-link">${esc(e.evaluatorName || e.evaluatorId)}</a>${e.standards && Object.keys(e.standards).length ? `<br><span style="font-size:11px;color:var(--muted)">${esc(formatStandardsLabel(e.standards))}</span>` : ""}</td>
          <td><span class="sev-tag" style="background:${sevColor}18;color:${sevColor};border-color:${sevColor}44">${esc(e.severity)}</span></td>
          <td><span class="verdict-tag ${verdictClass}">${evalVerdict}</span></td>
          <td>${e.total}</td>
          <td style="color:#059669;font-weight:600">${e.passed}</td>
          <td style="color:#DC2626;font-weight:600">${e.failed}</td>
          ${anyErrors ? `<td style="color:#D97706;font-weight:600">${e.errors > 0 ? e.errors : "—"}</td>` : ""}
          <td>${passRate}%</td>
          <td class="td-score">${avgScore !== "—" ? `${avgScore}<span style="color:#94A3B8">/10</span>` : "—"}</td>
        </tr>`;
    })
    .join("");

  // ── Evaluator detail appendix ─────────────────────────────────
  const appendix = evaluators
    .map((e, idx) => {
      const sevColor = SEV_HEX[e.severity] || "#64748B";
      const evalVerdict2 =
        e.errors > 0 && e.passed === 0 && e.failed === 0
          ? "ERROR"
          : e.failed === 0 && e.passed > 0
            ? "PASS"
            : "FAIL";
      const verdictClass2 =
        evalVerdict2 === "PASS"
          ? "verdict-pass"
          : evalVerdict2 === "ERROR"
            ? "verdict-error"
            : "verdict-fail";
      const cards = e.results.map((r, i) => resultCard(r, i, model.mode)).join("");
      return `
        <details class="eval-detail" id="eval-${idx}">
          <summary>
            <div class="eval-summary-left">
              <span class="eval-num">${String(idx + 1).padStart(2, "0")}</span>
              <div class="eval-summary-info">
                <span class="eval-summary-name">${esc(e.evaluatorName || e.evaluatorId)}</span>
                <span class="sev-tag" style="background:${sevColor}18;color:${sevColor};border-color:${sevColor}44">${esc(e.severity)}</span>
                ${e.standards && Object.keys(e.standards).length ? `<span style="font-size:11px;color:var(--muted)">${esc(formatStandardsLabel(e.standards))}</span>` : ""}
              </div>
            </div>
            <div class="eval-summary-right">
              <span style="font-size:12px;color:var(--muted)">${e.passed}/${e.total - e.errors} passed</span>
              <span class="verdict-tag ${verdictClass2}">${evalVerdict2}</span>
              <svg class="chevron" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 9l6 6 6-6"/></svg>
            </div>
          </summary>
          <div class="eval-body">
            ${cards}
          </div>
        </details>`;
    })
    .join("");

  // ── Cover meta items ──────────────────────────────────────────
  let coverMeta: string;
  if (model.mode === "agent") {
    coverMeta = `
      <div class="cover-meta-item"><div class="cover-meta-k">Target System</div><div class="cover-meta-v" title="${esc(target.name)}">${esc(truncate(target.name, 60))}</div></div>
      <div class="cover-meta-item"><div class="cover-meta-k">Endpoint</div><div class="cover-meta-v mono" style="font-family:ui-monospace,monospace;font-size:11px">${esc(truncate(target.endpoint ?? "", 60))}</div></div>
      <div class="cover-meta-item"><div class="cover-meta-k">Assessment Date</div><div class="cover-meta-v">${esc(dateStr)}, ${esc(timeStr)}</div></div>
      <div class="cover-meta-item"><div class="cover-meta-k">Generator Model</div><div class="cover-meta-v mono" style="font-family:ui-monospace,monospace;font-size:11px">${esc(model.generatorModel)}</div></div>
      <div class="cover-meta-item"><div class="cover-meta-k">Judge Model</div><div class="cover-meta-v mono" style="font-family:ui-monospace,monospace;font-size:11px">${esc(model.judgeModel)}</div></div>
      <div class="cover-meta-item"><div class="cover-meta-k">Report ID</div><div class="cover-meta-v mono" style="font-family:ui-monospace,monospace;font-size:11px;color:#94A3B8">${esc(model.reportId)}</div></div>`;
  } else {
    coverMeta = `
      <div class="cover-meta-item"><div class="cover-meta-k">Target Server</div><div class="cover-meta-v" title="${esc(target.name)}">${esc(truncate(target.name, 60))}</div></div>
      <div class="cover-meta-item"><div class="cover-meta-k">Evaluation Suite</div><div class="cover-meta-v">${esc(target.suiteId ?? "")}</div></div>
      <div class="cover-meta-item"><div class="cover-meta-k">Assessment Date</div><div class="cover-meta-v">${esc(dateStr)}, ${esc(timeStr)}</div></div>
      <div class="cover-meta-item"><div class="cover-meta-k">Generator Model</div><div class="cover-meta-v mono" style="font-family:ui-monospace,monospace;font-size:11px">${esc(model.generatorModel)}</div></div>
      <div class="cover-meta-item"><div class="cover-meta-k">Judge Model</div><div class="cover-meta-v mono" style="font-family:ui-monospace,monospace;font-size:11px">${esc(model.judgeModel)}</div></div>
      <div class="cover-meta-item"><div class="cover-meta-k">Report ID</div><div class="cover-meta-v mono" style="font-family:ui-monospace,monospace;font-size:11px;color:#94A3B8">${esc(model.reportId)}</div></div>`;
  }

  // ── Assessment scope section ──────────────────────────────────
  let scopeHtml: string;
  if (model.mode === "agent") {
    scopeHtml = `
      <div class="scope-card"><div class="scope-card-title">Target</div><div class="scope-row"><span class="scope-k">System</span><span class="scope-v">${esc(target.name)}</span></div><div class="scope-row"><span class="scope-k">Endpoint</span><span class="scope-v mono">${esc(truncate(target.endpoint ?? "", 60))}</span></div><div class="scope-row"><span class="scope-k">Type</span><span class="scope-v">${labels.typeLabel}</span></div></div>
      <div class="scope-card"><div class="scope-card-title">Evaluation Parameters</div><div class="scope-row"><span class="scope-k">Evaluators</span><span class="scope-v">${evaluators.length}</span></div><div class="scope-row"><span class="scope-k">Total Tests</span><span class="scope-v">${summary.total}</span></div><div class="scope-row"><span class="scope-k">Generator</span><span class="scope-v mono">${esc(model.generatorModel)}</span></div><div class="scope-row"><span class="scope-k">Judge</span><span class="scope-v mono">${esc(model.judgeModel)}</span></div></div>`;
  } else {
    scopeHtml = `
      <div class="scope-card"><div class="scope-card-title">Target</div><div class="scope-row"><span class="scope-k">Server</span><span class="scope-v mono">${esc(truncate(target.name, 80))}</span></div><div class="scope-row"><span class="scope-k">Transport</span><span class="scope-v">${esc(target.transport ?? "")}</span></div><div class="scope-row"><span class="scope-k">Total Attacks</span><span class="scope-v">${summary.total}</span></div></div>
      <div class="scope-card"><div class="scope-card-title">Evaluation Parameters</div><div class="scope-row"><span class="scope-k">Suite</span><span class="scope-v">${esc(target.suiteId ?? "")}</span></div><div class="scope-row"><span class="scope-k">Generator</span><span class="scope-v mono">${esc(model.generatorModel)}</span></div><div class="scope-row"><span class="scope-k">Judge</span><span class="scope-v mono">${esc(model.judgeModel)}</span></div><div class="scope-row"><span class="scope-k">Evaluators</span><span class="scope-v">${evaluators.length}</span></div></div>`;
  }

  // ── Narrative text ────────────────────────────────────────────
  let narrative: string;
  const targetLabel = model.mode === "agent" ? "target agent" : "MCP server";

  // For partial runs (stopReason OR errors with some real results), show simple warning
  if (model.stopReason && hasRealResults) {
    narrative = `<strong style="color:#D97706">⚠ Partial assessment.</strong> The run was stopped before all evaluators could complete.`;
  } else if (summary.errors > 0 && hasRealResults) {
    // Mixed results: some passed/failed, some errors (e.g., target failed mid-run)
    narrative = `<strong style="color:#D97706">⚠ Partial assessment.</strong> Some attacks failed due to target errors. Results below are from attacks that completed.`;
  } else if (overallVerdict === "ERROR") {
    if (model.stopReason && summary.total === 0) {
      narrative = `<strong style="color:#D97706">⚠ Assessment could not start.</strong> The run was stopped before any attacks could be executed.`;
    } else {
      narrative = `<strong style="color:#D97706">⚠ Assessment incomplete.</strong> All attacks failed due to errors. Please verify the target is accessible and retry.`;
    }
  } else if (overallVerdict === "PASS") {
    narrative = `The ${targetLabel} <strong>${esc(target.name)}</strong> passed all tests. No exploitable vulnerabilities were found.`;
  } else {
    narrative = `The ${targetLabel} <strong>${esc(target.name)}</strong> <strong>failed ${summary.failed} test${summary.failed === 1 ? "" : "s"}</strong>.${criticalFindings.length > 0 ? ` <strong style="color:#DC2626">${criticalFindings.length} critical</strong>.` : ""}`;
  }

  // ── Page title for <title> tag ────────────────────────────────
  const pageTitle =
    model.mode === "agent"
      ? `Opfor Agent Report — ${esc(target.name)}`
      : `Opfor MCP Report — ${esc(target.suiteId ?? target.name)}`;

  // ── Full HTML ─────────────────────────────────────────────────
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>${pageTitle}</title>
<style>
  :root{
    --bg:#F8FAFC;--surface:#FFFFFF;--surface-2:#F1F5F9;
    --text:#0F172A;--text-2:#334155;--muted:#64748B;--muted-2:#94A3B8;
    --line:#E2E8F0;--line-2:#CBD5E1;
    --pass:#059669;--pass-bg:#D1FAE5;--pass-border:#6EE7B7;
    --fail:#DC2626;--fail-bg:#FEE2E2;--fail-border:#FCA5A5;
    --accent:#f5ad5c;
  }
  *{box-sizing:border-box;margin:0;padding:0}
  html{background:var(--bg)}
  body{color:var(--text);font:14px/1.6 -apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;background:var(--bg);padding:0 0 60px}
  a{color:var(--accent);text-decoration:none}
  a:hover{text-decoration:underline}

  .page{max-width:960px;margin:0 auto;padding:0 24px}

  /* ── Cover band ── */
  .cover{background:#0F172A;color:#fff;padding:0;margin-bottom:32px}
  .cover-inner{max-width:960px;margin:0 auto;padding:36px 24px 32px}
  .cover-top{display:flex;align-items:flex-start;justify-content:space-between;gap:24px;margin-bottom:28px}
  .cover-brand{display:flex;align-items:center;gap:10px}
  .cover-brand-icon{width:36px;height:36px;background:linear-gradient(135deg,#f5ad5c,#c47a2a);border-radius:8px;display:flex;align-items:center;justify-content:center;flex-shrink:0}
  .cover-brand-name{font-size:15px;font-weight:700;letter-spacing:0.04em;color:#fff}
  .cover-brand-sub{font-size:11px;color:#94A3B8;letter-spacing:0.08em;text-transform:uppercase;margin-top:1px}
  .cover-classification{padding:4px 12px;border:1px solid rgba(255,255,255,0.15);border-radius:4px;font-size:11px;font-weight:600;letter-spacing:0.1em;text-transform:uppercase;color:#CBD5E1}
  .cover-title{font-size:26px;font-weight:700;color:#fff;letter-spacing:-0.01em;margin-bottom:6px}
  .cover-subtitle{font-size:14px;color:#94A3B8;margin-bottom:24px}
  .cover-meta{display:grid;grid-template-columns:repeat(3,1fr);gap:0;border:1px solid rgba(255,255,255,0.08);border-radius:10px;overflow:hidden}
  .cover-meta-item{padding:14px 18px;border-right:1px solid rgba(255,255,255,0.08)}
  .cover-meta-item:last-child{border-right:none}
  .cover-meta-k{font-size:11px;color:#64748B;text-transform:uppercase;letter-spacing:0.08em;margin-bottom:4px}
  .cover-meta-v{font-size:13px;color:#E2E8F0;font-weight:500;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}

  /* ── Section header ── */
  .section{margin-bottom:32px}
  .section-header{display:flex;align-items:center;gap:10px;margin-bottom:16px;padding-bottom:10px;border-bottom:1px solid var(--line)}
  .section-num{width:22px;height:22px;border-radius:6px;background:var(--accent);color:#fff;font-size:11px;font-weight:700;display:flex;align-items:center;justify-content:center;flex-shrink:0}
  .section-title{font-size:15px;font-weight:600;color:var(--text);letter-spacing:-0.01em}
  .section-subtitle{font-size:12px;color:var(--muted);margin-left:auto}

  /* ── Executive summary ── */
  .exec-banner{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:18px 20px;border-radius:12px;border:1px solid var(--line-2);background:var(--surface);margin-bottom:12px}
  .exec-banner.pass{border-color:var(--pass-border);background:var(--pass-bg)}
  .exec-banner.fail{border-color:var(--fail-border);background:var(--fail-bg)}
  .exec-banner.error{border-color:#FDE68A;background:#FFFBEB}
  .exec-banner-left{display:flex;align-items:center;gap:14px}
  .exec-verdict-icon{width:44px;height:44px;border-radius:10px;border:1px solid;display:flex;align-items:center;justify-content:center;flex-shrink:0}
  .exec-banner.pass .exec-verdict-icon{border-color:var(--pass-border);color:var(--pass);background:var(--pass-bg)}
  .exec-banner.fail .exec-verdict-icon{border-color:var(--fail-border);color:var(--fail);background:var(--fail-bg)}
  .exec-banner.error .exec-verdict-icon{border-color:#FDE68A;color:#D97706;background:#FEF3C7}
  .exec-verdict-label{font-size:11px;font-weight:600;letter-spacing:0.08em;text-transform:uppercase;color:var(--muted);margin-bottom:3px}
  .exec-verdict-text{font-size:26px;font-weight:800;letter-spacing:0.04em;line-height:1}
  .exec-banner.pass .exec-verdict-text{color:var(--pass)}
  .exec-banner.fail .exec-verdict-text{color:var(--fail)}
  .exec-banner.error .exec-verdict-text{color:#D97706}
  .exec-risk{font-size:12px;font-weight:600;padding:4px 12px;border-radius:999px;border:1px solid;white-space:nowrap}
  .exec-banner.pass .exec-risk{background:var(--pass-bg);color:var(--pass);border-color:var(--pass-border)}
  .exec-banner.fail .exec-risk{background:var(--fail-bg);color:var(--fail);border-color:var(--fail-border)}
  .exec-banner.error .exec-risk{background:#FEF3C7;color:#D97706;border-color:#FDE68A}
  .summary-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}
  .stat-card{background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:14px 16px}
  .stat-card .sc-label{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:0.06em;margin-bottom:6px}
  .stat-card .sc-value{font-size:22px;font-weight:700;line-height:1;color:var(--text)}
  .stat-card .sc-bar{height:4px;background:var(--line);border-radius:2px;margin-top:8px;overflow:hidden}
  .stat-card .sc-bar-fill{height:100%;border-radius:2px}
  .stat-card .sc-sub{font-size:11px;color:var(--muted);margin-top:4px}
  .summary-narrative{background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:16px;margin-top:12px;font-size:13px;color:var(--text-2);line-height:1.7}
  .summary-narrative strong{color:var(--text)}

  /* ── Assessment scope ── */
  .scope-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}
  .scope-card{background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:16px}
  .scope-card-title{font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.07em;color:var(--muted);margin-bottom:12px}
  .scope-row{display:flex;justify-content:space-between;align-items:baseline;gap:8px;padding:5px 0;border-bottom:1px solid var(--line)}
  .scope-row:last-child{border-bottom:none}
  .scope-k{font-size:12px;color:var(--muted);flex-shrink:0}
  .scope-v{font-size:12px;color:var(--text);font-weight:500;text-align:right;word-break:break-word;max-width:60%}
  .scope-v.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px}

  /* ── Findings ── */
  .findings-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}
  .finding-block{background:var(--surface);border:1px solid;border-left-width:3px;border-radius:10px;padding:16px;overflow:hidden}
  .finding-block-head{display:flex;align-items:center;gap:8px;margin-bottom:12px}
  .finding-label{font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:0.07em}
  .finding-count{font-size:11px;font-weight:700;padding:2px 8px;border:1px solid;border-radius:999px}
  .finding-list{margin:0;padding-left:18px;display:flex;flex-direction:column;gap:10px}
  .finding-list li{font-size:13px;color:var(--text-2);line-height:1.5}
  .finding-list strong{color:var(--text)}
  .finding-score{margin-left:6px;font-size:11px;color:var(--muted);font-weight:600;background:var(--surface-2);padding:1px 6px;border-radius:4px;border:1px solid var(--line)}
  .finding-desc{margin-top:3px;font-size:12px;color:var(--muted)}
  .no-findings{background:var(--pass-bg);border:1px solid var(--pass-border);border-radius:10px;padding:16px;text-align:center;color:var(--pass);font-weight:600;font-size:13px}

  /* ── Results table ── */
  .results-table-wrap{background:var(--surface);border:1px solid var(--line);border-radius:10px;overflow:hidden}
  table.results{width:100%;border-collapse:collapse}
  table.results th{background:var(--surface-2);padding:10px 14px;text-align:left;font-size:11px;font-weight:600;color:var(--muted);text-transform:uppercase;letter-spacing:0.06em;border-bottom:1px solid var(--line)}
  table.results td{padding:11px 14px;font-size:13px;border-bottom:1px solid var(--line);vertical-align:middle}
  table.results tr:last-child td{border-bottom:none}
  table.results tr:hover td{background:var(--surface-2)}
  .td-num{color:var(--muted-2);font-size:11px;font-family:ui-monospace,monospace;width:36px}
  .td-score{font-size:13px;font-weight:600;color:var(--text)}
  .eval-link{color:var(--text);font-weight:500}
  .eval-link:hover{color:var(--accent)}

  /* ── Badges ── */
  .sev-tag{display:inline-block;padding:2px 8px;border:1px solid;border-radius:4px;font-size:11px;font-weight:600;letter-spacing:0.03em;white-space:nowrap}
  .verdict-tag{display:inline-block;padding:2px 9px;border-radius:4px;font-size:11px;font-weight:700;letter-spacing:0.04em}
  .verdict-pass{background:var(--pass-bg);color:var(--pass);border:1px solid var(--pass-border)}
  .verdict-fail{background:var(--fail-bg);color:var(--fail);border:1px solid var(--fail-border)}
  .verdict-error{background:#FEF3C7;color:#D97706;border:1px solid #FDE68A}

  /* ── Evaluator detail blocks ── */
  .eval-detail{background:var(--surface);border:1px solid var(--line);border-radius:10px;overflow:hidden;margin-bottom:8px}
  .eval-detail > summary{display:flex;align-items:center;justify-content:space-between;padding:13px 16px;cursor:pointer;list-style:none;gap:12px}
  .eval-detail > summary::-webkit-details-marker{display:none}
  .eval-detail > summary:hover{background:var(--surface-2)}
  .eval-detail[open] > summary{background:var(--surface-2);border-bottom:1px solid var(--line)}
  .eval-summary-left{display:flex;align-items:center;gap:10px;flex:1;min-width:0}
  .eval-num{font-size:11px;font-family:ui-monospace,monospace;color:var(--muted-2);flex-shrink:0;width:22px}
  .eval-summary-info{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
  .eval-summary-name{font-size:13px;font-weight:600;color:var(--text)}
  .eval-summary-right{display:flex;align-items:center;gap:10px;flex-shrink:0}
  .chevron{color:var(--muted-2);transition:transform 0.2s;flex-shrink:0}
  .eval-detail[open] .chevron{transform:rotate(180deg)}
  .eval-body{padding:16px}

  /* ── Result cards ── */
  .result-card{border:1px solid var(--line);border-left:3px solid var(--line-2);border-radius:0 8px 8px 0;padding:12px 14px;margin-bottom:10px}
  .result-card.pass{border-left-color:var(--pass)}
  .result-card.fail{border-left-color:var(--fail)}
  .result-card.error{border-left-color:#F59E0B;background:#FFFDF5}
  .result-header{display:flex;align-items:center;gap:8px;margin-bottom:8px}
  .result-id{font-size:12px;font-weight:600;color:var(--text)}
  .result-tool{font-size:11px;color:var(--muted);font-family:ui-monospace,monospace}
  .result-section{margin-bottom:8px}
  .result-section-label{font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:0.06em;color:var(--muted);margin-bottom:4px}
  .result-code{font-size:12px;background:var(--surface-2);border:1px solid var(--line);padding:8px 10px;border-radius:6px;white-space:pre-wrap;word-break:break-word;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;max-height:400px;overflow:auto}
  .result-judge{margin-top:8px;font-size:12px;padding:8px 12px;border-radius:6px;border:1px solid var(--pass-border);background:var(--pass-bg);line-height:1.6}
  .result-judge.fail{background:var(--fail-bg);border-color:var(--fail-border)}

  /* ── Expandable code blocks ── */
  .code-wrap{position:relative;margin-top:4px}
  .code-wrap .result-code{max-height:180px;overflow:hidden;margin-top:0;border-radius:6px 6px 0 0;border-bottom:none}
  .code-wrap .code-fade{position:absolute;bottom:28px;left:0;right:0;height:48px;pointer-events:none}
  .code-wrap .code-more{display:block;width:100%;font-size:11px;font-weight:600;color:var(--muted);background:var(--surface);border:1px solid var(--line);border-radius:0 0 6px 6px;padding:4px 10px;cursor:pointer;text-align:center;letter-spacing:0.03em}
  .code-wrap .code-more:hover{background:var(--surface-2);color:var(--text)}
  .code-wrap.expanded .result-code{max-height:none;border-radius:6px 6px 0 0}
  .code-wrap.expanded .code-fade{display:none}
  .code-wrap.expanded .code-more{color:var(--muted-2)}

  /* ── Turn cards (multi-turn breakdown) ── */
  .turn-card{margin-bottom:8px;border:1px solid var(--line);border-radius:8px;overflow:hidden}
  .turn-card-header{display:flex;align-items:center;gap:8px;padding:7px 12px;background:var(--surface-2);cursor:pointer;list-style:none;font-size:11px;font-weight:600;color:var(--text);border-bottom:1px solid var(--line)}
  .turn-card-header::-webkit-details-marker{display:none}
  .turn-attacker{background:var(--surface-2);padding:10px 12px;border-bottom:1px solid var(--line);border-left:3px solid var(--accent)}
  .turn-attacker .turn-label{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.07em;color:var(--accent);margin-bottom:5px}
  .turn-attacker .code-wrap .result-code{background:var(--surface);border-color:var(--line)}
  .turn-attacker .code-more{background:var(--surface-2);border-color:var(--line)}
  .turn-attacker .code-more:hover{background:var(--surface)}
  .turn-agent{background:var(--surface);padding:10px 12px;border-left:3px solid var(--line-2)}
  .turn-agent .turn-label{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.07em;color:var(--muted);margin-bottom:5px}
  .turn-agent .code-wrap .result-code{background:var(--surface-2);border-color:var(--line)}
  .turn-agent .code-more{background:var(--surface);border-color:var(--line)}
  .turn-agent .code-more:hover{background:var(--surface-2)}
  .turn-reasoning{padding:7px 12px;background:var(--surface-2);border-top:1px solid var(--line);font-size:11px;color:var(--muted);font-style:italic;line-height:1.5}

  /* ── Footer ── */
  .report-footer{max-width:960px;margin:40px auto 0;padding:16px 24px;border-top:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}
  .footer-left{font-size:12px;color:var(--muted)}
  .footer-right{font-size:12px;color:var(--muted-2);font-family:ui-monospace,monospace}

  @media print{
    body{background:#fff;padding:0}
    .cover{-webkit-print-color-adjust:exact;print-color-adjust:exact}
    .eval-detail{border:1px solid var(--line)}
    .stat-card,.scope-card,.finding-block,.results-table-wrap,.eval-detail{break-inside:avoid;box-shadow:none}
  }
  @media(max-width:640px){
    .cover-meta{grid-template-columns:1fr 1fr}
    .exec-banner{flex-direction:column;align-items:flex-start}
    .summary-stats{grid-template-columns:1fr 1fr}
    .scope-grid,.findings-grid{grid-template-columns:1fr}
  }
</style>
</head>
<body>

<div class="cover">
  <div class="cover-inner">
    <div class="cover-top">
      <div class="cover-brand">
        <div class="cover-brand-icon">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2l8 4v6c0 5-3.5 9-8 10-4.5-1-8-5-8-10V6l8-4z"/></svg>
        </div>
        <div>
          <div class="cover-brand-name">Opfor</div>
          <div class="cover-brand-sub">${labels.brandSub}</div>
        </div>
      </div>
      <div class="cover-classification">Confidential</div>
    </div>
    <div class="cover-title">${labels.title}</div>
    <div class="cover-subtitle">Automated adversarial evaluation · opfor v0.2 · ${esc(dateStr)}</div>
    <div class="cover-meta">
      ${coverMeta}
    </div>
  </div>
</div>

<div class="page">

  <!-- 1. Executive Summary -->
  <div class="section">
    <div class="section-header">
      <div class="section-num">1</div>
      <div class="section-title">Executive Summary</div>
    </div>
    <div class="exec-banner ${overallVerdict === "PASS" ? "pass" : overallVerdict === "ERROR" ? "error" : "fail"}">
      <div class="exec-banner-left">
        <div class="exec-verdict-icon">
          ${
            overallVerdict === "PASS"
              ? `<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg>`
              : overallVerdict === "ERROR"
                ? `<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>`
                : `<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"><path d="M12 2l8 4v6c0 5-3.5 9-8 10-4.5-1-8-5-8-10V6l8-4z"/></svg>`
          }
        </div>
        <div>
          <div class="exec-verdict-label">Overall Verdict</div>
          <div class="exec-verdict-text">${overallVerdict}</div>
        </div>
      </div>
      <div class="exec-risk">${overallVerdict === "ERROR" ? "Inconclusive" : riskLevel.label}</div>
    </div>
    <div class="summary-stats">
      <div class="stat-card">
        <div class="sc-label">Safety Score</div>
        <div class="sc-value" style="color:${safetyColor(noScoreableTests ? 0 : summary.safetyScore)}">${noScoreableTests ? "N/A" : `${summary.safetyScore}%`}</div>
        ${noScoreableTests ? "" : `<div class="sc-bar"><div class="sc-bar-fill" style="width:${summary.safetyScore}%;background:${safetyColor(summary.safetyScore)}"></div></div>`}
        <div class="sc-sub">${noScoreableTests ? "No scoreable tests" : `${summary.passed} of ${scoreDenominator} attacks defended`}</div>
      </div>
      <div class="stat-card">
        <div class="sc-label">Attack Success Rate</div>
        <div class="sc-value" style="color:${summary.attackSuccessRate > 0 ? "#DC2626" : "#059669"}">${noScoreableTests ? "N/A" : `${summary.attackSuccessRate}%`}</div>
        ${noScoreableTests ? "" : `<div class="sc-bar"><div class="sc-bar-fill" style="width:${summary.attackSuccessRate}%;background:${summary.attackSuccessRate > 0 ? "#DC2626" : "#059669"}"></div></div>`}
        <div class="sc-sub">${summary.failed} attack${summary.failed !== 1 ? "s" : ""} breached defenses</div>
      </div>
      <div class="stat-card">
        <div class="sc-label">${labels.passedLabel}</div>
        <div class="sc-value" style="color:#059669">${summary.passed}</div>
        <div class="sc-sub">${labels.defendedLabel}</div>
      </div>
      <div class="stat-card">
        <div class="sc-label">Evaluators Failed</div>
        <div class="sc-value" style="color:${evalsFailed > 0 ? "#DC2626" : "#059669"}">${evalsFailed}</div>
        <div class="sc-sub">${criticalFindings.length} critical · ${highFindings.length} high</div>
      </div>
    </div>
    <div class="summary-narrative">
      ${narrative}
    </div>
  </div>

  <!-- 2. Assessment Scope -->
  <div class="section">
    <div class="section-header">
      <div class="section-num">2</div>
      <div class="section-title">Assessment Scope</div>
    </div>
    <div class="scope-grid">
      ${scopeHtml}
    </div>
  </div>

  <!-- 3. Findings -->
  ${
    criticalFindings.length + highFindings.length > 0
      ? `<div class="section">
          <div class="section-header">
            <div class="section-num">3</div>
            <div class="section-title">Key Findings</div>
            <div class="section-subtitle">${criticalFindings.length + highFindings.length} finding${criticalFindings.length + highFindings.length === 1 ? "" : "s"} requiring attention</div>
          </div>
          <div class="findings-grid">
            ${findingBlock("Critical", criticalFindings, "#DC2626")}
            ${findingBlock("High", highFindings, "#D97706")}
          </div>
        </div>`
      : `<div class="section">
          <div class="section-header">
            <div class="section-num">3</div>
            <div class="section-title">Key Findings</div>
          </div>
          <div class="no-findings">No critical or high severity findings — ${model.mode === "agent" ? "agent" : "server"} passed all evaluated attack patterns.</div>
        </div>`
  }

  <!-- 4. Evaluation Results -->
  <div class="section">
    <div class="section-header">
      <div class="section-num">4</div>
      <div class="section-title">Evaluation Results</div>
      <div class="section-subtitle">${evaluators.length} evaluator${evaluators.length === 1 ? "" : "s"} · ${summary.total} ${model.mode === "agent" ? "tests" : "attacks"}</div>
    </div>
    <div class="results-table-wrap" style="margin-bottom:16px">
      <table class="results">
        <thead><tr>
          <th>#</th><th>Evaluator</th><th>Severity</th><th>Verdict</th><th>Tests</th><th>Passed</th><th>Failed</th>${anyErrors ? "<th>Errors</th>" : ""}<th>Pass Rate</th><th>Avg Score</th>
        </tr></thead>
        <tbody>${tableRows}</tbody>
      </table>
    </div>
  </div>

  <!-- 5. Detailed Results -->
  <div class="section">
    <div class="section-header">
      <div class="section-num">5</div>
      <div class="section-title">${labels.detailSectionTitle}</div>
    </div>
    ${appendix}
  </div>

</div>

<div class="report-footer">
  <div class="footer-left">${labels.footerPrefix} · ${esc(dateStr)}</div>
  <div class="footer-right">${esc(model.reportId)}</div>
</div>

<script>
(function(){
  document.querySelectorAll('.code-wrap').forEach(function(wrap){
    var pre=wrap.querySelector('.result-code');
    if(pre&&pre.scrollHeight<=pre.clientHeight+4){
      wrap.querySelector('.code-fade').style.display='none';
      wrap.querySelector('.code-more').style.display='none';
    }
  });
})();
</script>
</body>
</html>`;
}

// ── Result card helper ───────────────────────────────────────────

function expandableBlock(content: string, fadeColor: string, extraStyle = ""): string {
  return `<div class="code-wrap">
    <pre class="result-code"${extraStyle ? ` style="${extraStyle}"` : ""}>${content}</pre>
    <div class="code-fade" style="background:linear-gradient(to bottom,${fadeColor}00,${fadeColor})"></div>
    <button class="code-more" onclick="var w=this.closest('.code-wrap');w.classList.toggle('expanded');this.textContent=w.classList.contains('expanded')?'▲ Show less':'▼ Show more'">▼ Show more</button>
  </div>`;
}

function renderDetailContent(detail: DetailCard, _mode: "agent" | "mcp"): string {
  if (detail.kind === "prompt") {
    return `
      <details class="result-section">
        <summary style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.07em;color:var(--accent);cursor:pointer;padding:2px 0">▸ Attacker Prompt</summary>
        ${expandableBlock(esc(truncate(detail.prompt, 8000)), "#F1F5F9")}
      </details>
      <details class="result-section">
        <summary style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.07em;color:var(--muted);cursor:pointer;padding:2px 0">▸ Agent Response</summary>
        ${expandableBlock(esc(truncate(detail.response, 8000)), "#F1F5F9")}
      </details>`;
  }
  const argsFormatted = esc(JSON.stringify(detail.args, null, 2));
  const responseText = detail.error
    ? `Error: ${esc(truncate(detail.error, 4000))}`
    : esc(truncate(detail.response, 8000));
  return `
    <details class="result-section">
      <summary style="font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.06em;color:var(--muted);cursor:pointer">Arguments</summary>
      ${expandableBlock(argsFormatted, "#F1F5F9")}
    </details>
    <details class="result-section">
      <summary style="font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.06em;color:var(--muted);cursor:pointer">Tool Response</summary>
      ${expandableBlock(responseText, "#F1F5F9")}
    </details>`;
}

function renderTurnContent(turn: TurnViewModel): string {
  const tVerdict = turn.judge?.verdict;
  const tColor =
    tVerdict === "PASS"
      ? "var(--pass)"
      : tVerdict === "ERROR"
        ? "#D97706"
        : tVerdict === "FAIL"
          ? "var(--fail)"
          : "var(--muted)";
  const borderColor = tVerdict ? tColor : "var(--line-2)";

  const verdictBadge = tVerdict
    ? `<span style="margin-left:auto;font-size:10px;font-weight:700;padding:1px 8px;border-radius:3px;background:${tVerdict === "PASS" ? "var(--pass-bg)" : tVerdict === "FAIL" ? "var(--fail-bg)" : "#FEF3C7"};color:${tColor};border:1px solid ${tVerdict === "PASS" ? "var(--pass-border)" : tVerdict === "FAIL" ? "var(--fail-border)" : "#FDE68A"}">${tVerdict}${tVerdict !== "ERROR" ? ` · ${turn.judge?.score}/10` : ""}</span>`
    : "";

  let detailHtml: string;
  if (turn.detail.kind === "prompt") {
    detailHtml = `
      <div class="turn-attacker">
        <div class="turn-label">Attacker Prompt</div>
        ${expandableBlock(esc(truncate(turn.detail.prompt, 8000)), "#F1F5F9")}
      </div>
      <div class="turn-agent">
        <div class="turn-label">Agent Response</div>
        ${expandableBlock(esc(truncate(turn.detail.response, 8000)), "#FFFFFF")}
      </div>`;
  } else {
    const tArgs = esc(JSON.stringify(turn.detail.args, null, 2));
    const tResp = turn.detail.error
      ? `Error: ${esc(truncate(turn.detail.error, 4000))}`
      : esc(truncate(turn.detail.response, 8000));
    const toolLabel = turn.detail.toolName
      ? ` · <code style="background:var(--surface-2);padding:1px 5px;border-radius:3px;font-size:10px">${esc(turn.detail.toolName)}</code>`
      : "";
    detailHtml = `
      <div class="turn-attacker">
        <div class="turn-label">Arguments${toolLabel}</div>
        ${expandableBlock(tArgs, "#F1F5F9")}
      </div>
      <div class="turn-agent">
        <div class="turn-label">Tool Response</div>
        ${expandableBlock(tResp, "#FFFFFF")}
      </div>`;
  }

  return `
    <details class="turn-card" open>
      <summary class="turn-card-header" style="border-left:3px solid ${borderColor}">
        <span style="font-family:ui-monospace,monospace;font-size:10px;color:var(--muted-2)">T${turn.turnIndex}</span>
        <span>Turn ${turn.turnIndex}</span>
        ${verdictBadge}
      </summary>
      ${detailHtml}
      ${turn.judge?.reasoning ? `<div class="turn-reasoning">${esc(turn.judge.reasoning)}</div>` : ""}
    </details>`;
}

function resultCard(r: ResultViewModel, index: number, mode: "agent" | "mcp"): string {
  const verdict = r.judge.verdict;
  const cardClass = verdict === "PASS" ? "pass" : verdict === "ERROR" ? "error" : "fail";
  const hasTurns = r.turns && r.turns.length > 0;

  // Header line
  let headerLabel: string;
  if (mode === "agent") {
    headerLabel = `<span class="result-id">Test ${r.id}: ${esc(r.label)}</span>`;
    if (r.traceId) {
      headerLabel += ` <span style="font-size:11px;color:var(--muted);font-family:ui-monospace,monospace">trace: ${esc(r.traceId.slice(0, 12))}…</span>`;
    }
  } else {
    headerLabel = `<span class="result-id">#${index + 1} ${esc(r.id)}</span><span class="result-tool">${esc(r.label)}</span>`;
  }

  // For multi-turn agent cards, skip the top-level prompt/response (it's shown in turns)
  const showTopDetail = !(mode === "agent" && hasTurns);

  // Turns HTML
  let turnsHtml = "";
  if (hasTurns) {
    turnsHtml = r.turns!.map((turn) => renderTurnContent(turn)).join("");
    turnsHtml = `
      <div class="result-section">
        <div class="result-section-label">Multi-turn breakdown (${r.turns!.length} turns)</div>
        ${turnsHtml}
      </div>`;
  }

  // Judge block
  const judgeBlock =
    verdict === "ERROR"
      ? `<div class="result-judge fail" style="background:#FFFBEB;border-color:#FDE68A;color:#92400E"><strong>ERROR:</strong> ${esc(r.judge.errorMessage ?? (r.detail.kind === "tool" ? (r.detail.error ?? "") : r.detail.response))}</div>`
      : `<div class="result-judge ${verdict === "FAIL" ? "fail" : ""}">
          <strong style="color:${verdict === "PASS" ? "var(--pass)" : "var(--fail)"}">${verdict}</strong>
          · Score ${r.judge.score}/10
          · Confidence ${r.judge.confidence}%
          ${r.judge.evidence && r.judge.evidence !== "N/A" ? `· Evidence: <em>${esc(truncate(r.judge.evidence, 200))}</em>` : ""}
          ${verdict === "FAIL" && hasTurns && r.judge.failingTurns && r.judge.failingTurns.length > 0 ? `· Failing turn${r.judge.failingTurns.length === 1 ? "" : "s"}: ${r.judge.failingTurns.join(", ")}` : ""}
          <br><span style="color:var(--text-2)">${esc(r.judge.reasoning)}</span>
        </div>`;

  const resultVerdictClass =
    verdict === "PASS" ? "verdict-pass" : verdict === "ERROR" ? "verdict-error" : "verdict-fail";
  return `
    <div class="result-card ${cardClass}">
      <div class="result-header">
        ${headerLabel}
        <span class="verdict-tag ${resultVerdictClass}" style="margin-left:auto">${verdict}</span>
      </div>
      ${showTopDetail ? renderDetailContent(r.detail, mode) : ""}
      ${turnsHtml}
      ${judgeBlock}
    </div>`;
}
