import type { Command } from "commander";
import { readFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { createModel } from "../providers/factory.js";
import { judgeResponse } from "../evaluators/judge.js";
import { generateReport } from "../report/generateReport.js";
import type { EvaluatorReport, TestResult } from "../report/generateReport.js";
import type { EvaluatorSpec } from "../evaluators/parseEvaluator.js";
import type { PromptsFile, AttackEntry } from "../config/types.js";
import type { RunAgentConfigHttp } from "../lib/agent.js";
import { runAttackAgent } from "../lib/agent.js";

export function registerRunCommand(program: Command) {
  program
    .command("run")
    .description("Execute an Astra scan from a prompts JSON file generated by `astra setup`")
    .requiredOption("--input <path>", "Path to the astra-prompts-*.json file from setup")
    .option("--output-dir <path>", "Directory to write HTML/JSON reports", ".astra/reports")
    .option("--concurrency <n>", "Max parallel attacks (default 1 — sequential)", "1")
    .option("--api-key <key>", "LLM API key (overrides the key stored in the prompts file)")
    .action(async (opts) => {
      // --- Load and validate the prompts file ---
      let promptsFile: PromptsFile;
      try {
        const raw = await readFile(path.resolve(opts.input), "utf8");
        promptsFile = JSON.parse(raw) as PromptsFile;
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        console.error(`Error reading prompts file: ${msg}`);
        process.exitCode = 1;
        return;
      }

      const { target, attacks } = promptsFile;
      const llm = {
        ...promptsFile.llm,
        ...(opts.apiKey ? { apiKey: opts.apiKey as string } : {}),
      };

      if (!attacks || attacks.length === 0) {
        console.error("No attack entries found in the prompts file. Run `astra setup` first.");
        process.exitCode = 1;
        return;
      }

      if (target.type === "http-endpoint" && !target.endpoint) {
        console.error("Target type is http-endpoint but no endpoint URL is specified in the prompts file.");
        process.exitCode = 1;
        return;
      }

      let model;
      try {
        model = createModel(llm);
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        console.error(`Error initialising LLM provider "${llm.provider}": ${msg}`);
        process.exitCode = 1;
        return;
      }

      const endpoint = target.endpoint ?? "";
      const targetFormat = target.requestFormat ?? "auto";
      const targetModel = target.targetModel ?? "gpt-4o-mini";
      const judgeLabel = `${llm.provider}/${llm.model}`;

      console.log(`\nAstra Run`);
      console.log(`  Target:     ${target.name}`);
      console.log(`  Endpoint:   ${endpoint || "(python-function)"}`);
      console.log(`  Provider:   ${judgeLabel}`);
      console.log(`  Attacks:    ${attacks.length}`);
      console.log(`  Report dir: ${opts.outputDir}`);
      console.log(``);

      // --- Group attacks by evaluator ---
      const byEvaluator = new Map<string, AttackEntry[]>();
      for (const attack of attacks) {
        const list = byEvaluator.get(attack.evaluatorId) ?? [];
        list.push(attack);
        byEvaluator.set(attack.evaluatorId, list);
      }

      const reports: EvaluatorReport[] = [];
      let totalRun = 0;

      for (const [evaluatorId, entries] of byEvaluator) {
        const first = entries[0];

        const evaluatorSpec: EvaluatorSpec = {
          id: evaluatorId,
          name: first.evaluatorName,
          severity: first.severity,
          owasp: first.owasp,
          description: "",
          passCriteria: first.passCriteria,
          failCriteria: first.failCriteria,
          patterns: [],
        };

        console.log(`\n[${first.owasp}] ${first.evaluatorName} (${entries.length} attack${entries.length !== 1 ? "s" : ""})`);

        const results: TestResult[] = [];
        let testNumber = 1;

        for (const attack of entries) {
          process.stdout.write(
            `  [${testNumber}/${entries.length}] ${attack.patternName.slice(0, 55).padEnd(55)}`
          );

          if (target.type === "http-endpoint") {
            const agentCfg: RunAgentConfigHttp = {
              attack,
              targetApiKey: target.targetApiKey,
              model,
              endpoint,
              targetFormat,
              targetModel,
            };

            const result = await runAttackAgent(agentCfg);
            const verdict = result.judge.verdict === "PASS" ? "✓" : "✗";
            console.log(` → ${verdict} ${result.judge.verdict} (score ${result.judge.score}/10)`);

            results.push({
              testNumber: totalRun + testNumber,
              pattern: attack.patternName,
              prompt: attack.prompt,
              response: result.response,
              judge: result.judge,
            });
          } else {
            const judgeResult = await judgeResponse(
              evaluatorSpec,
              attack.prompt,
              "(python-function target — no HTTP call made; manual review required)",
              model
            );
            console.log(` → SKIPPED (python-function target)`);
            results.push({
              testNumber: totalRun + testNumber,
              pattern: attack.patternName,
              prompt: attack.prompt,
              response: "(python-function — manual review required)",
              judge: judgeResult,
            });
          }

          testNumber++;
        }

        totalRun += entries.length;
        reports.push({ evaluator: evaluatorSpec, results });
      }

      // --- Generate report ---
      console.log(`\nGenerating report...`);
      const outputDir = path.resolve(opts.outputDir);
      await mkdir(outputDir, { recursive: true });

      const paths = await generateReport(
        reports,
        target.name,
        endpoint || "(python-function)",
        outputDir,
        judgeLabel
      );

      const passCount = reports.flatMap(r => r.results).filter(r => r.judge.verdict === "PASS").length;
      const failCount = totalRun - passCount;
      const score = totalRun > 0 ? Math.round((passCount / totalRun) * 100) : 0;

      console.log(`\nRun complete!`);
      console.log(`  Total attacks: ${totalRun}`);
      console.log(`  Passed:        ${passCount}`);
      console.log(`  Failed:        ${failCount}`);
      console.log(`  Safety score:  ${score}%`);
      console.log(`\nReports:`);
      console.log(`  HTML: ${paths.html}`);
      console.log(`  JSON: ${paths.json}\n`);
    });
}
